// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/5/2025, 12:46:18 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/projects/sb1-jb6pj94m/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-jb6pj94m/composables/**/*.{js,ts,mjs}","/home/projects/sb1-jb6pj94m/utils/**/*.{js,ts,mjs}","/home/projects/sb1-jb6pj94m/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-jb6pj94m/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;